### ISSUE TITLE
Fix the request error on the symptoms screen

### ISSUE THREAD

**Issue by genesis9432** [BC-NOV-20-Proyectos/alerta-covid-mobile-team-01#25]
# REQUIREMENTS
Correct the error that appears when sending the symptoms on the symptoms screen

# DESIGN
![image](https://user-images.githubusercontent.com/73856947/117034387-e035f000-acc8-11eb-9475-df7756ac7e39.png)

# Acceptance Criteria

- [ ] Correct submission of symptoms
- [ ] Good quality code

**Comment by Joaquin-Niembro** [comment]
Issue seems to work fine, returning status 200 now.
